# Generated by Django 3.0.8 on 2020-07-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20200712_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='EUR Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('bilingName', models.CharField(blank=True, max_length=250)),
                ('bilingAddress1', models.CharField(blank=True, max_length=250)),
                ('bilingCity', models.CharField(blank=True, max_length=250)),
                ('bilingPostcode', models.CharField(blank=True, max_length=250)),
                ('bilingCountry', models.CharField(blank=True, max_length=250)),
                ('ShippingName', models.CharField(blank=True, max_length=250)),
                ('ShippingAddress1', models.CharField(blank=True, max_length=250)),
                ('ShippingCity', models.CharField(blank=True, max_length=250)),
                ('ShippingPostcode', models.CharField(blank=True, max_length=250)),
                ('ShippingCountry', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='EUR Total')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
